<a href="https://colab.research.google.com/github/Brunoopdev/Colab_Python_study/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estudo de NumPy para data science e análise de dados pelo google colab

Importa o Numpy e coloca um apelido para melhor manipulação

In [4]:
import numpy as np

Cria um array com o Numpy, tem que colocar o array com colchetes dentro das aspas do método array do Numpy e poderia ser um set, tupla, um dicionário ou um array comum do python.

In [9]:
teste = np.array([1,2,3,4,5,6,7])

Verifica a versão do Numpy

In [13]:
print(np.__version__)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


Verificando o tipo de dado de um array aqui no numpy, que retorna
* numpy.ndarray

In [14]:
print(type(teste))

<class 'numpy.ndarray'>


* Arrays 0-D são arrays que possuem apenas um elemento dentro.

* Arrays 1-D são os mais comuns que possuem alguns elementos dentro de um array.

* Arrays 2-D são aqueles que possuem um array dentro de um array

* Arrays 3-D são aqueles que possuem dois arrays 2-d dentro de um array

---

Dessa forma conseguimos identificar as dimensões de um array em numpy

In [60]:
array0d = np.array([42])
array1d = np.array([1,2,3,4,5,6,7,8,9,10])
array2d = np.array([[1,2,3,4,5], [5,4,3,2,1]])
array3d = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[10,9,8,7,6],[5,4,3,2,1]]])

print(array0d, '\n')
print(array1d, '\n')
print(array2d, '\n')
print(array3d)

[42] 

[ 1  2  3  4  5  6  7  8  9 10] 

[[1 2 3 4 5]
 [5 4 3 2 1]] 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[10  9  8  7  6]
  [ 5  4  3  2  1]]]


Conseguimos delimitar o número de dimensões ao definir um array em numpy, fazemos isso usando o comando

* *ndmin = quantidadeDeDimensões*

Por exemplo, um array de 5 dimensões.

E para verificar a quantidade de dimensões, usamos o comando:
* *array.ndim*



In [27]:
array5d = np.array([1,2,3,4,5], ndmin = 5)

print(array5d)

print("número de dimensões é:", array5d.ndim)

[[[[[1 2 3 4 5]]]]]
número de dimensões é: 5


Para acessar um elemento dentro de um array feito por Numpy, funciona da mesma forma que no python puro.

* print(teste[0])

Já para acessar um elemento dentro de um array que tenha mais dimensões, podemos acessar escolhendo qual é o array e qual é o posicionamento do elemento:

* print(array2d[0,1]) -> Por exemplo nesse caso o 0 escolhe o primeiro array, e o 1 depois da vírgula escolhe o elemento que esteja na posição 1

* print(array2d[1,1]) -> Já nesse exemplo, escolhemos o segundo array e o elemento que esteja na posição 1

In [42]:
acessoElemento = np.array([1,2,3,4,5,6,7,8,9,10])
print(acessoElemento)
print('O elemento que está na posição 0 do array acima é:', acessoElemento[0], '\n\n')

print(array2d)
print('A posição do primeiro array e do elemento em posição 1 é:', array2d[0,1])
print('A posição do segundo array e do elemento em posição 1 é:', array2d[1,1])

[ 1  2  3  4  5  6  7  8  9 10]
O elemento que está na posição 0 do array acima é: 1 


[[1 2 3 4 5]
 [5 4 3 2 1]]
A posição do primeiro array e do elemento em posição 1 é: 2
A posição do segundo array e do elemento em posição 1 é: 4


Já para acessar um elemento em um array que possui 3 dimensões, funciona assim:

* print(array3d[0,1,2]) -> O primeiro 0 significa qual dos arrays 2d entraremos, o 1 significa qual dos arrays dentro dos arrays 2d vamos entrar, e o 2 significa qual posição de elemento queremos buscar.

In [65]:
print(array3d, '\n\n')
print('O elemento da posição 2 no segundo array dentro do primeiro array 2D:',array3d[0,1,2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[10  9  8  7  6]
  [ 5  4  3  2  1]]] 


O elemento da posição 2 no segundo array dentro do primeiro array 2D: 8


Com index negativos, conseguimos selecionar o último elemento dentro de um array.

* print(array2d[0,-1]) -> O 0 significa escolher o primeiro array dentro de um array2d e o -1 significa escolher o último elemento do array.

In [73]:
print(array2d, '\n\n')
print('O último elemento do segundo array dentro do array 2d é:', array2d[0,-1])

[[1 2 3 4 5]
 [5 4 3 2 1]] 


O último elemento do segundo array dentro do array 2d é: 5


Podemos cortar um array em um pedaço para usar como bem entender, e funciona assim:

* print(array1d[0:5]) -> O 0 pega o elemento de posição 0 e o 5 elemento de posição 5 e retira, portanto esse array que tem 10 elementos, vai exibir apenas do elemento 0 até o elemento 4, pois o ultimo elemento não conta.

E conseguimos cortar do primeiro elemento até qualquer um que queremos, de forma automárica, fazendo isso ocultando o primeiro elemento:

* print(array1d[:5]) -> Dessa forma fazemos exatamente como o caso acima.

In [77]:
print(array1d, '\n\n')
print(array1d[0:5], '\n') # Usando o método exibindo o primeiro elemento e o qual queremos
print(array1d[:5]) # Usando o método de ocultar o primeiro elemento, apenas selecionamos o qual queremos

[ 1  2  3  4  5  6  7  8  9 10] 


[1 2 3 4 5] 

[1 2 3 4 5]
