<a href="https://colab.research.google.com/github/Brunoopdev/Colab_Python_study/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estudo de NumPy para data science e análise de dados pelo google colab

Importa o Numpy e coloca um apelido para melhor manipulação

In [4]:
import numpy as np

Cria um array com o Numpy, tem que colocar o array com colchetes dentro das aspas do método array do Numpy e poderia ser um set, tupla, um dicionário ou um array comum do python.

In [9]:
teste = np.array([1,2,3,4,5,6,7])

Verifica a versão do Numpy

In [13]:
print(np.__version__)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


Verificando o tipo de dado de um array aqui no numpy, que retorna
* numpy.ndarray

In [14]:
print(type(teste))

<class 'numpy.ndarray'>


* Arrays 0-D são arrays que possuem apenas um elemento dentro.

* Arrays 1-D são os mais comuns que possuem alguns elementos dentro de um array.

* Arrays 2-D são aqueles que possuem um array dentro de um array

* Arrays 3-D são aqueles que possuem dois arrays 2-d dentro de um array

---

Dessa forma conseguimos identificar as dimensões de um array em numpy

In [21]:
array0d = np.array([42])
array1d = np.array([1,2,3,4,5,6,7,8,9,10])
array2d = np.array([[1,2,3,4,5], [5,4,3,2,1]])
array3d = np.array([[1,2,3,4,5], [6,7,8,9,10],[10,9,8,7,6],[5,4,3,2,1]])

print(array0d, '\n')
print(array1d, '\n')
print(array2d, '\n')
print(array3d)

[42] 

[ 1  2  3  4  5  6  7  8  9 10] 

[[1 2 3 4 5]
 [5 4 3 2 1]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


Conseguimos delimitar o número de dimensões ao definir um array em numpy, fazemos isso usando o comando

* *ndmin = quantidadeDeDimensões*

Por exemplo, um array de 5 dimensões.

E para verificar a quantidade de dimensões, usamos o comando:
* *array.ndim*



In [27]:
array5d = np.array([1,2,3,4,5], ndmin = 5)

print(array5d)

print("número de dimensões é:", array5d.ndim)

[[[[[1 2 3 4 5]]]]]
número de dimensões é: 5
